# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elevation', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('trailaccess', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Sort of')], max_length=1)),
            ],
        ),
    ]
