# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lake',
            name='trailaccess',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Sort of'), ('R', 'Road Access')], max_length=1),
        ),
    ]
