# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0002_auto_20181030_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lake',
            name='lon',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
