# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0004_auto_20181030_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
    ]
