# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0005_auto_20181030_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
