# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0006_auto_20181030_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drainage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flowsinto', models.CharField(max_length=100)),
                ('terminal', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='lake',
            name='drainages',
            field=models.ManyToManyField(blank=True, to='lakes.Drainage'),
        ),
    ]
