# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0007_auto_20181031_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainage',
            name='lakesdrained',
            field=models.ManyToManyField(blank=True, to='lakes.Lake'),
        ),
    ]
