# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0008_drainage_lakesdrained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lake',
            name='drainages',
        ),
    ]
