# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0009_remove_lake_drainages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drainage',
            old_name='flowsinto',
            new_name='flows_into',
        ),
        migrations.RemoveField(
            model_name='drainage',
            name='lakesdrained',
        ),
        migrations.AddField(
            model_name='lake',
            name='drainages',
            field=models.ManyToManyField(blank=True, to='lakes.Drainage'),
        ),
    ]
