# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0010_auto_20181031_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drainage',
            name='flows_into',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
