# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0012_lake_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
