# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0013_lake_slug'),
        ('lakes', '0014_lake_slug'),
    ]

    operations = [
    ]
