# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0015_merge_20181113_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='image1',
            field=models.ImageField(null=True, upload_to='lake_images'),
        ),
    ]
