# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0017_auto_20181116_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lake',
            name='image1',
        ),
        migrations.AddField(
            model_name='lake',
            name='image',
            field=models.ImageField(blank=True, upload_to='lake_images'),
        ),
    ]
