# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-19 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0018_auto_20181118_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='imagedate',
            field=models.DateField(null=True),
        ),
    ]
