# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0019_lake_imagedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='lakeoutline',
            field=models.ImageField(blank=True, upload_to='lakeoutlines'),
        ),
        migrations.AddField(
            model_name='lake',
            name='locationmap',
            field=models.ImageField(blank=True, upload_to='locationmaps'),
        ),
    ]
