# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0020_auto_20181129_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='imagedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
